# -*- coding: utf-8 -*-
"""Day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xgu9oioLwAFgpEstfHka1LeBSSh6VotY
"""

# Day3 Assignment
gift_presented_to = [2, 1, 5, 3, 4]
gift_presented_to[0]=2
gift_presented_to[1]=1
gift_presented_to[2]=4
gift_presented_to[3]=5
gift_presented_to[4]=3
print('gift_recieved_from:',gift_presented_to)