# -*- coding: utf-8 -*-
"""DAY 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16w72l_ZXlaZ1GNxDtqqkv1E22E83L6SF
"""

x= input('Enter values : ')
print(type(x))

li= [int(i) for i in x.split()]
print(li)
li.reverse()
print(li)

