# -*- coding: utf-8 -*-
"""Day 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/187dTMxGEWVrlI7xOmx7aDEJiorL1TSrD
"""

# Day 4(Final Project)
def convert(c):
  f=(c * 9/5)+32
  return f
res=convert(50)
print("Fahrenheit: ",res)